name: Build and deploy ASP.Net Core app to Azure Web App - service-one

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        include-prerelease: true

    - name: Build with dotnet
      run: dotnet build -c ${{env.BUILD_CONFIGURATION}}

    - name: dotnet publish
      run: dotnet publish -c ${{env.BUILD_CONFIGURATION}} src/Service-One.Web -o ${{env.DOTNET_ROOT}}/myapp

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/myapp
  
  unit_tests:
    runs-on: ubuntu-latest      

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.1

      - name: run tests
        run: dotnet test -c ${{env.BUILD_CONFIGURATION}}

  deploy-dev:
    runs-on: ubuntu-latest
    needs: 
      - build
      - unit_tests
    environment:
      name: 'dev'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: .net-app

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'service-one'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b6a300ac738f4191be4784c94492396d }}
        package: .
    
    - uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIAL_TEST }}'
    
    - uses: azure/appservice-settings@v1
      with:
        app-name: 'service-one'
        mask-inputs: false
        app-settings-json: |
          [
            {
              "name": "ServiceTwoUrl",
              "value": "https://service-two.azurewebsites.net/api/",
              "slotSetting": false
            }
          ]
    
    - run: |
        az logout